/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroprodutos.ui;

import cadastroprodutos.controller.CompraController;
import cadastroprodutos.controller.ProdutoController;
import cadastroprodutos.model.Compra;
import cadastroprodutos.model.Produto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class FrameCadastroCompra extends javax.swing.JFrame {

    private DefaultTableModel modeloTabela;
    private CompraController cc = new CompraController();
    private ProdutoController pc = new ProdutoController();
    private Compra compra = new Compra();
    
    /**
     * Creates new form FrameCadastroCompra
     */
    public FrameCadastroCompra() {
        initComponents();
        limpar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSalvarCompra = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        lbCodigoProcurar = new javax.swing.JLabel();
        btProcurarProduto = new javax.swing.JButton();
        tfCodigoProcurar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItensCompra = new javax.swing.JTable();
        lbCadastroCompra = new javax.swing.JLabel();
        lbDataCompra = new javax.swing.JLabel();
        tfDataCompra = new javax.swing.JFormattedTextField();
        lbTotal = new javax.swing.JLabel();
        tfTotalCompra = new javax.swing.JFormattedTextField();
        tfQuantidade = new javax.swing.JTextField();
        lbQuantidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSalvarCompra.setText("Salvar Compra");
        btSalvarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarCompraActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        lbCodigoProcurar.setText("Código do produto a comprar:");

        btProcurarProduto.setText("Procurar");
        btProcurarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarProdutoActionPerformed(evt);
            }
        });

        tbItensCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Preço", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(tbItensCompra);

        lbCadastroCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCadastroCompra.setText("Cadastro de Compra");

        lbDataCompra.setText("Data da compra:");

        tfDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm"))));
        tfDataCompra.setEnabled(false);

        lbTotal.setText("Total da compra:");

        tfTotalCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        tfTotalCompra.setEnabled(false);

        lbQuantidade.setText("Quantidade a comprar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lbCadastroCompra))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(lbTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btSalvarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(lbDataCompra)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbCodigoProcurar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfCodigoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbQuantidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btProcurarProduto))))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCadastroCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfDataCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoProcurar)
                    .addComponent(tfCodigoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidade)
                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProcurarProduto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotal)
                    .addComponent(tfTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarCompra)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarCompraActionPerformed
            cc.cadastrar(compra);
            
            JOptionPane.showMessageDialog(this, "Compra registrada com sucesso!");
            limpar();
    }//GEN-LAST:event_btSalvarCompraActionPerformed

    private void limpar() {
        //limpar o formulario
        compra = new Compra();
        modeloTabela = new DefaultTableModel();
        modeloTabela.addColumn("Código produto");
        modeloTabela.addColumn("Nome do produto");
        modeloTabela.addColumn("Preço individual");
        modeloTabela.addColumn("Quantidade");
        modeloTabela.addColumn("Preço Total");
        
        tbItensCompra.setModel(modeloTabela);
        
        tfDataCompra.setText(compra.getData());
        
        tfCodigoProcurar.setText("");    
    }    
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btProcurarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarProdutoActionPerformed
        int codProduto = Integer.parseInt(tfCodigoProcurar.getText());
        int quantidade = Integer.parseInt(tfQuantidade.getText());
        
            Produto p = pc.obterProduto(codProduto);

            if(p == null) {
                JOptionPane.showMessageDialog(this, 
                        "Produto não encontrado!");
                tfQuantidade.setText("");
                tfCodigoProcurar.setText("");
                tfCodigoProcurar.requestFocus();
                return;
            }
            //adiciona o produto a compra
            compra.adicionar(p, quantidade);
            
            //atualiza a tabela itens de compra
            Object[] dados = new Object[5];
                
            dados[0] = codProduto;
            dados[1] = p.getDescricaoProd();
            dados[2] = p.getPrecoVenda();
            dados[3] = quantidade;
            dados[4] = quantidade * p.getPrecoVenda();
                
            modeloTabela.addRow(dados);
            modeloTabela.fireTableDataChanged();
            
            tfTotalCompra.setText(
                    Double.toString(compra.getTotal()));
            
            tfQuantidade.setText("");
            tfCodigoProcurar.setText("");
            tfCodigoProcurar.requestFocus();  
        
    }//GEN-LAST:event_btProcurarProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btProcurarProduto;
    private javax.swing.JButton btSalvarCompra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCadastroCompra;
    private javax.swing.JLabel lbCodigoProcurar;
    private javax.swing.JLabel lbDataCompra;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tbItensCompra;
    private javax.swing.JTextField tfCodigoProcurar;
    private javax.swing.JFormattedTextField tfDataCompra;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JFormattedTextField tfTotalCompra;
    // End of variables declaration//GEN-END:variables
}
