/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroprodutos.ui;

import cadastroprodutos.controller.ProdutoController;
import cadastroprodutos.model.Produto;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.*;

public class FrameTabela extends javax.swing.JFrame {

    Produto produto;
    ProdutoController produtoController;
    List<Produto> listaProdutos;
    DefaultTableModel dtm;
    
    public FrameTabela() {
        initComponents();
        
        dtm = new DefaultTableModel();
        dtm.addColumn("Codigo");
        dtm.addColumn("Nome");
        dtm.addColumn("Preco");

        jTable1.setModel(dtm);
        
        produto = new Produto();
        produtoController = new ProdutoController();
        
        listaProdutos = produtoController.obterProdutos();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btAlterarCodigo = new javax.swing.JButton();
        btAlterarPreco = new javax.swing.JButton();
        btAlterarNome = new javax.swing.JButton();
        btAlterarCodigo1 = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        lbCodigoProcurar = new javax.swing.JLabel();
        btProcurarProduto = new javax.swing.JButton();
        tfCodigoProcurar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Preço", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lista de Produtos");

        btAlterarCodigo.setText("Ordernar por codigo");
        btAlterarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarCodigoActionPerformed(evt);
            }
        });

        btAlterarPreco.setText("Ordernar por preço");
        btAlterarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarPrecoActionPerformed(evt);
            }
        });

        btAlterarNome.setText("Ordernar por nome");
        btAlterarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarNomeActionPerformed(evt);
            }
        });

        btAlterarCodigo1.setText("Alterar");
        btAlterarCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarCodigo1ActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        lbCodigoProcurar.setText("Código do produto a procurar:");

        btProcurarProduto.setText("Procurar");
        btProcurarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCodigoProcurar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodigoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btProcurarProduto))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btAlterarCodigo)
                                    .addGap(42, 42, 42)
                                    .addComponent(btAlterarNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btAlterarPreco))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btAlterarCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(72, 72, 72)
                                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87))))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoProcurar)
                    .addComponent(btProcurarProduto)
                    .addComponent(tfCodigoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAlterarCodigo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAlterarPreco)
                        .addComponent(btAlterarNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAlterarCodigo1)
                    .addComponent(btRemover))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarCodigoActionPerformed
        listaProdutos = produtoController.obterProdutos();
        //ordenar minha lista
        Collections.sort(listaProdutos);
        preencherTabela();
    }//GEN-LAST:event_btAlterarCodigoActionPerformed

    private void btAlterarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarPrecoActionPerformed
        listaProdutos = produtoController.obterProdutos();
        //como ordenar por preco?
        ComparadorProdutoPorPreco cpp = new ComparadorProdutoPorPreco();
        listaProdutos.sort(cpp);
        preencherTabela();
    }//GEN-LAST:event_btAlterarPrecoActionPerformed

    private void btAlterarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarNomeActionPerformed
        listaProdutos = produtoController.obterProdutos();

        ComparadorProdutoPorNome cpn = new ComparadorProdutoPorNome();
        listaProdutos.sort(cpn);
        preencherTabela();
    }//GEN-LAST:event_btAlterarNomeActionPerformed

    private void btAlterarCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarCodigo1ActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();
        Produto p = listaProdutos.get(linhaSelecionada);
        FrameAlterar fp = new FrameAlterar(p);
        fp.setVisible(true);
    }//GEN-LAST:event_btAlterarCodigo1ActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();
        Produto p = listaProdutos.get(linhaSelecionada);
        produtoController.remover(p.getCodProduto());
        listaProdutos.remove(linhaSelecionada);
        preencherTabela();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btProcurarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarProdutoActionPerformed
        int codigo = Integer.parseInt(tfCodigoProcurar.getText());
        Produto p = new Produto();
        p.setCodProduto(codigo);
        int posicao = listaProdutos.indexOf(p);
        if(posicao < 0) {
            JOptionPane.showMessageDialog(this, 
                    "Não existe produto com o código informado.");
        } else {
            jTable1.setRowSelectionInterval(posicao, posicao);
        }
    }//GEN-LAST:event_btProcurarProdutoActionPerformed

    
    private void preencherTabela(){
        ProdutoTabelaModelo modelo = new ProdutoTabelaModelo(listaProdutos);
        jTable1.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarCodigo;
    private javax.swing.JButton btAlterarCodigo1;
    private javax.swing.JButton btAlterarNome;
    private javax.swing.JButton btAlterarPreco;
    private javax.swing.JButton btProcurarProduto;
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbCodigoProcurar;
    private javax.swing.JTextField tfCodigoProcurar;
    // End of variables declaration//GEN-END:variables
}
